{% set version = "1.7.1" %}

package:
  name: ql
  version: {{ version }}

source:
  git_url: https://github.com/lballabio/QuantLib.git
  git_tag: QuantLib-v1.7.1
  patches:
    - win_ql_settings.patch           [win]

build:
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py35]

requirements:
  build:
    - python
    - boost
    - six
  run:
    - boost

about:
  home: http://quantlib.org/
  license: OSI
  summary: QuantLib - the free/open-source library for quantitative finance

extra:
  recipe-maintainers:
    - TonyRoberts
